openapi: '3.0.0'
info:
  version: 1.0.0
  title: React Tokyo Olympic 2020
servers:
  - url: http:/localhost:8080
paths:
  /country_infos:
    get:
      operationId: country_infos
      responses:
        '200':
          description: ''
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CountryInfo'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /medal_count_countries:
    get:
      operationId: medal_count_countries
      responses:
        '200':
          description: ''
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MedalCountCountry'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    PageInfo:
      type: object
      required:
        - per_page
        - page_number
        - total_page_count
        - total_count
        - first_cursor_id
        - last_cursor_id
        - has_previous_page
        - has_next_page
      properties:
        per_page:
          type: integer
          format: int64
        page_number:
          type: integer
          format: int64
        total_page_count:
          type: integer
          format: int64
        total_count:
          type: integer
          format: int64
        first_cursor_id:
          type: integer
          format: int64
        last_cursor_id:
          type: integer
          format: int64
        has_previous_page:
          type: boolean
        has_next_page:
          type: boolean
    MedalType:
      type: number
      enum:
        - 1
        - 2
        - 3
      x-enum-varnames:
        - gold
        - silver
        - bronze
    CountryInfo:
      type: object
      required:
        - id
        - alpha_2_code
        - name
        - capital
        - flag
      properties:
        id:
          type: integer
          format: int64
        alpha_2_code:
          type: string
        name:
          type: string
        capital:
          type: string
        flag:
          type: string
        languages:
          type: array
          items:
            type: object
            required:
              - name
            properties:
              name:
                type: string
        translations:
          type: object
          properties:
            ja:
              type: string
        region:
          type: string
        subregion:
          type: string
        population:
          type: integer
          format: int64
    MedalCountCountry:
      type: object
      required:
        - id
        - country_alpha_2_code
        - gold_count
        - silver_count
        - bronze_count
      properties:
        id:
          type: integer
          format: int64
        country_alpha_2_code:
          type: string
        gold_count:
          type: integer
          format: int32
        silver_count:
          type: integer
          format: int32
        bronze_count:
          type: integer
          format: int32
