import { MedalCountCountry } from '~/generated/api'

export const medalCountCountries = (): MedalCountCountry[] => [
  {
    id: 1,
    country_alpha_2_code: 'cn',
    gold_count: 14,
    silver_count: 6,
    bronze_count: 9,
  },
  {
    id: 2,
    country_alpha_2_code: 'us',
    gold_count: 13,
    silver_count: 13,
    bronze_count: 10,
  },
  {
    id: 3,
    country_alpha_2_code: 'jp',
    gold_count: 13,
    silver_count: 4,
    bronze_count: 5,
  },
  {
    id: 4,
    country_alpha_2_code: 'ru',
    gold_count: 7,
    silver_count: 11,
    bronze_count: 7,
  },
  {
    id: 5,
    country_alpha_2_code: 'au',
    gold_count: 7,
    silver_count: 2,
    bronze_count: 10,
  },
  {
    id: 6,
    country_alpha_2_code: 'gb',
    gold_count: 5,
    silver_count: 6,
    bronze_count: 5,
  },
  {
    id: 7,
    country_alpha_2_code: 'kr',
    gold_count: 4,
    silver_count: 2,
    bronze_count: 5,
  },
  {
    id: 8,
    country_alpha_2_code: 'de',
    gold_count: 3,
    silver_count: 3,
    bronze_count: 5,
  },
  {
    id: 9,
    country_alpha_2_code: 'fr',
    gold_count: 3,
    silver_count: 3,
    bronze_count: 3,
  },
  {
    id: 10,
    country_alpha_2_code: 'it',
    gold_count: 2,
    silver_count: 7,
    bronze_count: 9,
  },
  {
    id: 11,
    country_alpha_2_code: 'nl',
    gold_count: 2,
    silver_count: 7,
    bronze_count: 4,
  },
  {
    id: 12,
    country_alpha_2_code: 'ca',
    gold_count: 2,
    silver_count: 3,
    bronze_count: 5,
  },
  {
    id: 13,
    country_alpha_2_code: 'hu',
    gold_count: 2,
    silver_count: 1,
    bronze_count: 2,
  },
  {
    id: 14,
    country_alpha_2_code: 'si',
    gold_count: 2,
    silver_count: 1,
    bronze_count: 1,
  },
  {
    id: 15,
    country_alpha_2_code: 'hr',
    gold_count: 2,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 16,
    country_alpha_2_code: 'xk',
    gold_count: 2,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 17,
    country_alpha_2_code: 'ch',
    gold_count: 1,
    silver_count: 3,
    bronze_count: 2,
  },
  {
    id: 18,
    country_alpha_2_code: 'ro',
    gold_count: 1,
    silver_count: 3,
    bronze_count: 0,
  },
  {
    id: 19,
    country_alpha_2_code: 'tw',
    gold_count: 1,
    silver_count: 2,
    bronze_count: 3,
  },
  {
    id: 20,
    country_alpha_2_code: 'br',
    gold_count: 1,
    silver_count: 2,
    bronze_count: 2,
  },
  {
    id: 21,
    country_alpha_2_code: 'nz',
    gold_count: 1,
    silver_count: 2,
    bronze_count: 1,
  },
  {
    id: 22,
    country_alpha_2_code: 'ge',
    gold_count: 1,
    silver_count: 2,
    bronze_count: 0,
  },
  {
    id: 23,
    country_alpha_2_code: 'rs',
    gold_count: 1,
    silver_count: 1,
    bronze_count: 2,
  },
  {
    id: 24,
    country_alpha_2_code: 'at',
    gold_count: 1,
    silver_count: 1,
    bronze_count: 1,
  },
  {
    id: 25,
    country_alpha_2_code: 'hk',
    gold_count: 1,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 26,
    country_alpha_2_code: 'tn',
    gold_count: 1,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 27,
    country_alpha_2_code: 'ee',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 28,
    country_alpha_2_code: 'ie',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 29,
    country_alpha_2_code: 'uz',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 30,
    country_alpha_2_code: 'bm',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 31,
    country_alpha_2_code: 'ec',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 32,
    country_alpha_2_code: 'fj',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 33,
    country_alpha_2_code: 'ir',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 34,
    country_alpha_2_code: 'lv',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 35,
    country_alpha_2_code: 'no',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 36,
    country_alpha_2_code: 'ph',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 37,
    country_alpha_2_code: 'th',
    gold_count: 1,
    silver_count: 0,
    bronze_count: 0,
  },
  {
    id: 38,
    country_alpha_2_code: 'es',
    gold_count: 0,
    silver_count: 2,
    bronze_count: 1,
  },
  {
    id: 39,
    country_alpha_2_code: 'za',
    gold_count: 0,
    silver_count: 2,
    bronze_count: 0,
  },
  {
    id: 40,
    country_alpha_2_code: 'id',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 2,
  },
  {
    id: 41,
    country_alpha_2_code: 'mn',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 2,
  },
  {
    id: 42,
    country_alpha_2_code: 'be',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 1,
  },
  {
    id: 43,
    country_alpha_2_code: 'cz',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 1,
  },
  {
    id: 44,
    country_alpha_2_code: 'dk',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 1,
  },
  {
    id: 45,
    country_alpha_2_code: 'bg',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 46,
    country_alpha_2_code: 'co',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 47,
    country_alpha_2_code: 'in',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 48,
    country_alpha_2_code: 'jo',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 49,
    country_alpha_2_code: 'mk',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 50,
    country_alpha_2_code: 'pl',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 51,
    country_alpha_2_code: 'tm',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 52,
    country_alpha_2_code: 've',
    gold_count: 0,
    silver_count: 1,
    bronze_count: 0,
  },
  {
    id: 53,
    country_alpha_2_code: 'ua',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 4,
  },
  {
    id: 54,
    country_alpha_2_code: 'kz',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 3,
  },
  {
    id: 55,
    country_alpha_2_code: 'eg',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 2,
  },
  {
    id: 56,
    country_alpha_2_code: 'mx',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 2,
  },
  {
    id: 57,
    country_alpha_2_code: 'tr',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 2,
  },
  {
    id: 58,
    country_alpha_2_code: 'ar',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 59,
    country_alpha_2_code: 'ci',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 60,
    country_alpha_2_code: 'cu',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 61,
    country_alpha_2_code: 'fi',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 62,
    country_alpha_2_code: 'il',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
  {
    id: 63,
    country_alpha_2_code: 'kw',
    gold_count: 0,
    silver_count: 0,
    bronze_count: 1,
  },
]
